### ISSUE TITLE
Possible to flash WPalaControl onto Palazzetti CBOX?

### ISSUE THREAD

**Issue by tanc** [Domochip/WPalaControl#53]
Just wondering if you know whether there is a way to flash WPalaControl onto the Palazzetti CBOX? I have the FTDI FT232RL USB to TTL adapter which I use to communicate with the stove. Is it possible to use this to flash the CBOX? If so do you know which pins need connecting?

**Comment by Domochip** [comment]
It is not possible to flash the WPalaControl firmware on a CBox.
They are using a completely different CPU/technology.

**Comment by tanc** [comment]
No problem, thanks for letting me know so quickly
