### ISSUE TITLE
Feature request: Expose the firebox temp to Home Assistant

### ISSUE THREAD

**Issue by tanc** [Domochip/WPalaControl#61]
For my nerdy graph needs it would be great to expose the T3 temp to Home Assistant so that I can monitor the relationship between the tank temp and the firebox temp.

```
{
    "INFO": {
        "CMD": "GET TMPS",
        "RSP": "OK"
    },
    "DATA": {
        "T1": 71.9, <-- Tank or outflow temp
        "T2": 63.9, <-- Inflow temp
        "T3": 210, <-- Firebox temp
        "T4": 0,
        "T5": 18 <-- Room temp
    },
    "SUCCESS": true
}
```

**Comment by Domochip** [comment]
It's added in the current master branch as a disabled by default one

**Comment by BorisNanev** [comment]
"T3": 210, <-- Firebox temp is important for monitoring how stove works and when exhaust gases go too much UP is indicator that your stove is for cleaning (i mean inside of waste box).

**Comment by tanc** [comment]
> It's added in the current master branch as a disabled by default one

Should I be able to see it and enable it in Home Assistant already? Or do you mean it needs to be enabled in code first?

**Comment by BorisNanev** [comment]
i cant see it in HA. only in browser of domochip.

**Comment by Domochip** [comment]
@BorisNanev It is in master branch not part of the current release. You need to compile and flash it in your module if you want to see it

@tanc it will be created in Home Assistant but you'll need to go to the device and enable this entity, then you'll be able to use it like any other

**Comment by Domochip** [comment]
going to the stove device, you can find some grayed out sensors, and enable them : 
![image](https://github.com/user-attachments/assets/77751546-c159-455f-832b-4c290a6c8d2a)
![image](https://github.com/user-attachments/assets/1fe51c38-a56d-44d7-ab4c-87384b820413)
![image](https://github.com/user-attachments/assets/6de14d41-870f-46dc-9c9d-31c6f299b113)

**Comment by BorisNanev** [comment]
I know, I enabled all sensors in home assistant but I don't have T3. I can a see it in browser but not in hove assistant .

**Comment by Domochip** [comment]
You'll find the version containing these new sensors in the latest pre-release (3.4.0)
https://github.com/Domochip/WPalaControl/releases

**Comment by BorisNanev** [comment]
That's awesome. Thanks one more time. I was looking for this from years. :)

**Comment by Domochip** [comment]
@tanc @BorisNanev Does everything looks good for you?
I'm considering switch the current pre-release as release

**Comment by BorisNanev** [comment]
I don't have any issues with pre-release. Everything works perfectly. I do have some random disconnects for 2-3 seconds 3-4 time per day, same as stable release.(I think it's not from bad WiFi connection coz router and device show good connection). It's not big of deal for me.

**Comment by Domochip** [comment]
@BorisNanev thank you for the feeback.
Regarding the disconnection, I have it sometime and sometime not (3 days without it on my side now...)
I was not able to catch it yet.
Could you confirm me this behavior : 
 - in Home assistant, both Stove and WPalaControl connectivity disconnect and reconnect
 - in WPalaControl webpage, the UpTime is not resetted

**Comment by BorisNanev** [comment]
Yes, I can confirm. 35 hours without disconnection. I didn't check UpTime but I will next time.

**Comment by Domochip** [comment]
ok, I'll close this issue.
Regarding the disconnection, it is still very hard to figure out now.
I'll have a look at this later when I've time.

**Comment by tanc** [comment]
Sorry I wasn't able to test, but just wanted to say thanks, I did the update today and can confirm the fluegas sensor is now available (after enabling it)
