### ISSUE TITLE
Synchronization 

### ISSUE THREAD

**Issue by BorisNanev** [Domochip/WPalaControl#64]
Is it possible to synchronize the date and time from domochip to stove? (thats my first topic I made in GitHub so I'm sorry if this Is wrong section)

**Comment by Domochip** [comment]
you can change the stove time using the command SET+TIME
=> https://github.com/Domochip/WPalaControl?tab=readme-ov-file#command-list

**Comment by BorisNanev** [comment]
Thanks, I'm not familiar how to do it but I'll figure out.
